version: '3'

services:
  nginx:
    volumes:
      - ./nginx/sandbox/conf.d/kafka_manager.addon:/etc/nginx/conf.d/kafka_manager.addon
    depends_on:
      - kafka_manager

  kafka:
    environment:
      JMX_PORT: 9999
#      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka -Dcom.sun.management.jmxremote.rmi.port=9999"

  kafka_manager:
    image: sheepkiller/kafka-manager
    environment:
      ZK_HOSTS: "zookeeper:2181"
      KM_CONFIGFILE: "/opt/application.conf"
    volumes:
      - ./kafka_manager/sandbox/conf/application.conf:/opt/application.conf
  #    ports:
  #      - "9000:9000"
    depends_on:
      - zookeeper
      - kafka
    networks:
      - dig_net

  mydig_ws:
    environment:
      ADDON_KAFKA_MANAGER: "true"
